docker-change-net /usr/bin
docker-change-net-sudoers /etc/sudoers.d
translations/es/LC_MESSAGES/docker-change-net.mo /usr/share/locale/es_ES/LC_MESSAGES
translations/es/LC_MESSAGES/docker-change-net.mo /usr/share/locale/es_ES.UTF-8/LC_MESSAGES
translations/va/LC_MESSAGES/docker-change-net.mo /usr/share/locale/ca_ES/LC_MESSAGES
translations/va/LC_MESSAGES/docker-change-net.mo /usr/share/locale/ca_ES.UTF-8/LC_MESSAGES
translations/va/LC_MESSAGES/docker-change-net.mo /usr/share/locale/ca_ES@valencia/LC_MESSAGES
blacklist.txt /usr/share/docker-change-net
